# Generated by Django 6.1 on 2026-09-12 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=150)),
                ('origin_farm', models.CharField(max_length=200)),
                ('destination', models.CharField(default='Por definir', max_length=200)),
                ('harvest_date', models.DateField()),
                ('current_status', models.CharField(choices=[('Registrado', 'Registrado'), ('En proceso', 'En proceso'), ('En tránsito', 'En tránsito'), ('Completado', 'Completado'), ('Retenido por Calidad', 'Retenido por Calidad')], default='En proceso', max_length=50)),
                ('temperature_avg', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('humidity_avg', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('quality_cert', models.CharField(default='En auditoría', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('operator', models.CharField(default='Operador Logístico', max_length=150)),
                ('status', models.CharField(default='Completado', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='traceability.batch')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
